"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class Axes:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, x: Incomplete | None = None, y: Incomplete | None = None) -> None:
        """Axes - a model defined in OpenAPI."""
        ...
    @property
    def x(self):
        """
        Get the x of this Axes.

        :return: The x of this Axes.
        :rtype: Axis
        """
        ...
    @x.setter
    def x(self, x) -> None:
        """
        Get the x of this Axes.

        :return: The x of this Axes.
        :rtype: Axis
        """
        ...
    @property
    def y(self):
        """
        Get the y of this Axes.

        :return: The y of this Axes.
        :rtype: Axis
        """
        ...
    @y.setter
    def y(self, y) -> None:
        """
        Get the y of this Axes.

        :return: The y of this Axes.
        :rtype: Axis
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
