"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class BucketRetentionRules:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self, type: str = "expire", every_seconds: int = 2592000, shard_group_duration_seconds: int | None = None
    ) -> None:
        """BucketRetentionRules - a model defined in OpenAPI."""
        ...
    @property
    def type(self):
        """
        Get the type of this BucketRetentionRules.

        :return: The type of this BucketRetentionRules.
        :rtype: str
        """
        ...
    @type.setter
    def type(self, type) -> None:
        """
        Get the type of this BucketRetentionRules.

        :return: The type of this BucketRetentionRules.
        :rtype: str
        """
        ...
    every_seconds: int
    @property
    def shard_group_duration_seconds(self):
        """
        Get the shard_group_duration_seconds of this BucketRetentionRules.

        The shard group duration. The duration or interval (in seconds) that each shard group covers.  #### InfluxDB Cloud  - Does not use `shardGroupDurationsSeconds`.  #### InfluxDB OSS  - Default value depends on the [bucket retention period](https://docs.influxdata.com/influxdb/latest/reference/internals/shards/#shard-group-duration).

        :return: The shard_group_duration_seconds of this BucketRetentionRules.
        :rtype: int
        """
        ...
    @shard_group_duration_seconds.setter
    def shard_group_duration_seconds(self, shard_group_duration_seconds) -> None:
        """
        Get the shard_group_duration_seconds of this BucketRetentionRules.

        The shard group duration. The duration or interval (in seconds) that each shard group covers.  #### InfluxDB Cloud  - Does not use `shardGroupDurationsSeconds`.  #### InfluxDB OSS  - Default value depends on the [bucket retention period](https://docs.influxdata.com/influxdb/latest/reference/internals/shards/#shard-group-duration).

        :return: The shard_group_duration_seconds of this BucketRetentionRules.
        :rtype: int
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
