"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from influxdb_client.domain.expression import Expression

class CallExpression(Expression):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self, type: Incomplete | None = None, callee: Incomplete | None = None, arguments: Incomplete | None = None
    ) -> None:
        """CallExpression - a model defined in OpenAPI."""
        ...
    @property
    def type(self):
        """
        Get the type of this CallExpression.

        Type of AST node

        :return: The type of this CallExpression.
        :rtype: str
        """
        ...
    @type.setter
    def type(self, type) -> None:
        """
        Get the type of this CallExpression.

        Type of AST node

        :return: The type of this CallExpression.
        :rtype: str
        """
        ...
    @property
    def callee(self):
        """
        Get the callee of this CallExpression.

        :return: The callee of this CallExpression.
        :rtype: Expression
        """
        ...
    @callee.setter
    def callee(self, callee) -> None:
        """
        Get the callee of this CallExpression.

        :return: The callee of this CallExpression.
        :rtype: Expression
        """
        ...
    @property
    def arguments(self):
        """
        Get the arguments of this CallExpression.

        Function arguments

        :return: The arguments of this CallExpression.
        :rtype: list[Expression]
        """
        ...
    @arguments.setter
    def arguments(self, arguments) -> None:
        """
        Get the arguments of this CallExpression.

        Function arguments

        :return: The arguments of this CallExpression.
        :rtype: list[Expression]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
