"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class DashboardColor:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        id: Incomplete | None = None,
        type: Incomplete | None = None,
        hex: Incomplete | None = None,
        name: Incomplete | None = None,
        value: Incomplete | None = None,
    ) -> None:
        """DashboardColor - a model defined in OpenAPI."""
        ...
    @property
    def id(self):
        """
        Get the id of this DashboardColor.

        The unique ID of the view color.

        :return: The id of this DashboardColor.
        :rtype: str
        """
        ...
    @id.setter
    def id(self, id) -> None:
        """
        Get the id of this DashboardColor.

        The unique ID of the view color.

        :return: The id of this DashboardColor.
        :rtype: str
        """
        ...
    @property
    def type(self):
        """
        Get the type of this DashboardColor.

        Type is how the color is used.

        :return: The type of this DashboardColor.
        :rtype: str
        """
        ...
    @type.setter
    def type(self, type) -> None:
        """
        Get the type of this DashboardColor.

        Type is how the color is used.

        :return: The type of this DashboardColor.
        :rtype: str
        """
        ...
    @property
    def hex(self):
        """
        Get the hex of this DashboardColor.

        The hex number of the color

        :return: The hex of this DashboardColor.
        :rtype: str
        """
        ...
    @hex.setter
    def hex(self, hex) -> None:
        """
        Get the hex of this DashboardColor.

        The hex number of the color

        :return: The hex of this DashboardColor.
        :rtype: str
        """
        ...
    @property
    def name(self):
        """
        Get the name of this DashboardColor.

        The user-facing name of the hex color.

        :return: The name of this DashboardColor.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this DashboardColor.

        The user-facing name of the hex color.

        :return: The name of this DashboardColor.
        :rtype: str
        """
        ...
    @property
    def value(self):
        """
        Get the value of this DashboardColor.

        The data value mapped to this color.

        :return: The value of this DashboardColor.
        :rtype: float
        """
        ...
    @value.setter
    def value(self, value) -> None:
        """
        Get the value of this DashboardColor.

        The data value mapped to this color.

        :return: The value of this DashboardColor.
        :rtype: float
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
