"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class DBRPUpdate:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, retention_policy: Incomplete | None = None, default: Incomplete | None = None) -> None:
        """DBRPUpdate - a model defined in OpenAPI."""
        ...
    @property
    def retention_policy(self):
        """
        Get the retention_policy of this DBRPUpdate.

        A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp) name. Identifies the InfluxDB v1 retention policy mapping.

        :return: The retention_policy of this DBRPUpdate.
        :rtype: str
        """
        ...
    @retention_policy.setter
    def retention_policy(self, retention_policy) -> None:
        """
        Get the retention_policy of this DBRPUpdate.

        A [retention policy](https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#retention-policy-rp) name. Identifies the InfluxDB v1 retention policy mapping.

        :return: The retention_policy of this DBRPUpdate.
        :rtype: str
        """
        ...
    @property
    def default(self):
        """
        Get the default of this DBRPUpdate.

        Set to `true` to use this DBRP mapping as the default retention policy for the database (specified by the `database` property's value). To remove the default mapping, set to `false`.

        :return: The default of this DBRPUpdate.
        :rtype: bool
        """
        ...
    @default.setter
    def default(self, default) -> None:
        """
        Get the default of this DBRPUpdate.

        Set to `true` to use this DBRP mapping as the default retention policy for the database (specified by the `database` property's value). To remove the default mapping, set to `false`.

        :return: The default of this DBRPUpdate.
        :rtype: bool
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
