"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from influxdb_client.domain.check_discriminator import CheckDiscriminator

class DeadmanCheck(CheckDiscriminator):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        type: str = "deadman",
        time_since: Incomplete | None = None,
        stale_time: Incomplete | None = None,
        report_zero: Incomplete | None = None,
        level: Incomplete | None = None,
        every: Incomplete | None = None,
        offset: Incomplete | None = None,
        tags: Incomplete | None = None,
        status_message_template: Incomplete | None = None,
        id: Incomplete | None = None,
        name: Incomplete | None = None,
        org_id: Incomplete | None = None,
        task_id: Incomplete | None = None,
        owner_id: Incomplete | None = None,
        created_at: Incomplete | None = None,
        updated_at: Incomplete | None = None,
        query: Incomplete | None = None,
        status: Incomplete | None = None,
        description: Incomplete | None = None,
        latest_completed: Incomplete | None = None,
        last_run_status: Incomplete | None = None,
        last_run_error: Incomplete | None = None,
        labels: Incomplete | None = None,
        links: Incomplete | None = None,
    ) -> None:
        """DeadmanCheck - a model defined in OpenAPI."""
        ...
    @property
    def type(self):
        """
        Get the type of this DeadmanCheck.

        :return: The type of this DeadmanCheck.
        :rtype: str
        """
        ...
    @type.setter
    def type(self, type) -> None:
        """
        Get the type of this DeadmanCheck.

        :return: The type of this DeadmanCheck.
        :rtype: str
        """
        ...
    @property
    def time_since(self):
        """
        Get the time_since of this DeadmanCheck.

        String duration before deadman triggers.

        :return: The time_since of this DeadmanCheck.
        :rtype: str
        """
        ...
    @time_since.setter
    def time_since(self, time_since) -> None:
        """
        Get the time_since of this DeadmanCheck.

        String duration before deadman triggers.

        :return: The time_since of this DeadmanCheck.
        :rtype: str
        """
        ...
    @property
    def stale_time(self):
        """
        Get the stale_time of this DeadmanCheck.

        String duration for time that a series is considered stale and should not trigger deadman.

        :return: The stale_time of this DeadmanCheck.
        :rtype: str
        """
        ...
    @stale_time.setter
    def stale_time(self, stale_time) -> None:
        """
        Get the stale_time of this DeadmanCheck.

        String duration for time that a series is considered stale and should not trigger deadman.

        :return: The stale_time of this DeadmanCheck.
        :rtype: str
        """
        ...
    @property
    def report_zero(self):
        """
        Get the report_zero of this DeadmanCheck.

        If only zero values reported since time, trigger an alert

        :return: The report_zero of this DeadmanCheck.
        :rtype: bool
        """
        ...
    @report_zero.setter
    def report_zero(self, report_zero) -> None:
        """
        Get the report_zero of this DeadmanCheck.

        If only zero values reported since time, trigger an alert

        :return: The report_zero of this DeadmanCheck.
        :rtype: bool
        """
        ...
    @property
    def level(self):
        """
        Get the level of this DeadmanCheck.

        :return: The level of this DeadmanCheck.
        :rtype: CheckStatusLevel
        """
        ...
    @level.setter
    def level(self, level) -> None:
        """
        Get the level of this DeadmanCheck.

        :return: The level of this DeadmanCheck.
        :rtype: CheckStatusLevel
        """
        ...
    @property
    def every(self):
        """
        Get the every of this DeadmanCheck.

        Check repetition interval.

        :return: The every of this DeadmanCheck.
        :rtype: str
        """
        ...
    @every.setter
    def every(self, every) -> None:
        """
        Get the every of this DeadmanCheck.

        Check repetition interval.

        :return: The every of this DeadmanCheck.
        :rtype: str
        """
        ...
    @property
    def offset(self):
        """
        Get the offset of this DeadmanCheck.

        Duration to delay after the schedule, before executing check.

        :return: The offset of this DeadmanCheck.
        :rtype: str
        """
        ...
    @offset.setter
    def offset(self, offset) -> None:
        """
        Get the offset of this DeadmanCheck.

        Duration to delay after the schedule, before executing check.

        :return: The offset of this DeadmanCheck.
        :rtype: str
        """
        ...
    @property
    def tags(self):
        """
        Get the tags of this DeadmanCheck.

        List of tags to write to each status.

        :return: The tags of this DeadmanCheck.
        :rtype: list[object]
        """
        ...
    @tags.setter
    def tags(self, tags) -> None:
        """
        Get the tags of this DeadmanCheck.

        List of tags to write to each status.

        :return: The tags of this DeadmanCheck.
        :rtype: list[object]
        """
        ...
    @property
    def status_message_template(self):
        """
        Get the status_message_template of this DeadmanCheck.

        The template used to generate and write a status message.

        :return: The status_message_template of this DeadmanCheck.
        :rtype: str
        """
        ...
    @status_message_template.setter
    def status_message_template(self, status_message_template) -> None:
        """
        Get the status_message_template of this DeadmanCheck.

        The template used to generate and write a status message.

        :return: The status_message_template of this DeadmanCheck.
        :rtype: str
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
