"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from influxdb_client.domain.view_properties import ViewProperties

class MosaicViewProperties(ViewProperties):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        time_format: Incomplete | None = None,
        type: Incomplete | None = None,
        queries: Incomplete | None = None,
        colors: Incomplete | None = None,
        shape: Incomplete | None = None,
        note: Incomplete | None = None,
        show_note_when_empty: Incomplete | None = None,
        x_column: Incomplete | None = None,
        generate_x_axis_ticks: Incomplete | None = None,
        x_total_ticks: Incomplete | None = None,
        x_tick_start: Incomplete | None = None,
        x_tick_step: Incomplete | None = None,
        y_label_column_separator: Incomplete | None = None,
        y_label_columns: Incomplete | None = None,
        y_series_columns: Incomplete | None = None,
        fill_columns: Incomplete | None = None,
        x_domain: Incomplete | None = None,
        y_domain: Incomplete | None = None,
        x_axis_label: Incomplete | None = None,
        y_axis_label: Incomplete | None = None,
        x_prefix: Incomplete | None = None,
        x_suffix: Incomplete | None = None,
        y_prefix: Incomplete | None = None,
        y_suffix: Incomplete | None = None,
        hover_dimension: Incomplete | None = None,
        legend_colorize_rows: Incomplete | None = None,
        legend_hide: Incomplete | None = None,
        legend_opacity: Incomplete | None = None,
        legend_orientation_threshold: Incomplete | None = None,
    ) -> None:
        """MosaicViewProperties - a model defined in OpenAPI."""
        ...
    @property
    def time_format(self):
        """
        Get the time_format of this MosaicViewProperties.

        :return: The time_format of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @time_format.setter
    def time_format(self, time_format) -> None:
        """
        Get the time_format of this MosaicViewProperties.

        :return: The time_format of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def type(self):
        """
        Get the type of this MosaicViewProperties.

        :return: The type of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @type.setter
    def type(self, type) -> None:
        """
        Get the type of this MosaicViewProperties.

        :return: The type of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def queries(self):
        """
        Get the queries of this MosaicViewProperties.

        :return: The queries of this MosaicViewProperties.
        :rtype: list[DashboardQuery]
        """
        ...
    @queries.setter
    def queries(self, queries) -> None:
        """
        Get the queries of this MosaicViewProperties.

        :return: The queries of this MosaicViewProperties.
        :rtype: list[DashboardQuery]
        """
        ...
    @property
    def colors(self):
        """
        Get the colors of this MosaicViewProperties.

        Colors define color encoding of data into a visualization

        :return: The colors of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @colors.setter
    def colors(self, colors) -> None:
        """
        Get the colors of this MosaicViewProperties.

        Colors define color encoding of data into a visualization

        :return: The colors of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @property
    def shape(self):
        """
        Get the shape of this MosaicViewProperties.

        :return: The shape of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @shape.setter
    def shape(self, shape) -> None:
        """
        Get the shape of this MosaicViewProperties.

        :return: The shape of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def note(self):
        """
        Get the note of this MosaicViewProperties.

        :return: The note of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @note.setter
    def note(self, note) -> None:
        """
        Get the note of this MosaicViewProperties.

        :return: The note of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def show_note_when_empty(self):
        """
        Get the show_note_when_empty of this MosaicViewProperties.

        If true, will display note when empty

        :return: The show_note_when_empty of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @show_note_when_empty.setter
    def show_note_when_empty(self, show_note_when_empty) -> None:
        """
        Get the show_note_when_empty of this MosaicViewProperties.

        If true, will display note when empty

        :return: The show_note_when_empty of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @property
    def x_column(self):
        """
        Get the x_column of this MosaicViewProperties.

        :return: The x_column of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @x_column.setter
    def x_column(self, x_column) -> None:
        """
        Get the x_column of this MosaicViewProperties.

        :return: The x_column of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def generate_x_axis_ticks(self):
        """
        Get the generate_x_axis_ticks of this MosaicViewProperties.

        :return: The generate_x_axis_ticks of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @generate_x_axis_ticks.setter
    def generate_x_axis_ticks(self, generate_x_axis_ticks) -> None:
        """
        Get the generate_x_axis_ticks of this MosaicViewProperties.

        :return: The generate_x_axis_ticks of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @property
    def x_total_ticks(self):
        """
        Get the x_total_ticks of this MosaicViewProperties.

        :return: The x_total_ticks of this MosaicViewProperties.
        :rtype: int
        """
        ...
    @x_total_ticks.setter
    def x_total_ticks(self, x_total_ticks) -> None:
        """
        Get the x_total_ticks of this MosaicViewProperties.

        :return: The x_total_ticks of this MosaicViewProperties.
        :rtype: int
        """
        ...
    @property
    def x_tick_start(self):
        """
        Get the x_tick_start of this MosaicViewProperties.

        :return: The x_tick_start of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @x_tick_start.setter
    def x_tick_start(self, x_tick_start) -> None:
        """
        Get the x_tick_start of this MosaicViewProperties.

        :return: The x_tick_start of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @property
    def x_tick_step(self):
        """
        Get the x_tick_step of this MosaicViewProperties.

        :return: The x_tick_step of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @x_tick_step.setter
    def x_tick_step(self, x_tick_step) -> None:
        """
        Get the x_tick_step of this MosaicViewProperties.

        :return: The x_tick_step of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @property
    def y_label_column_separator(self):
        """
        Get the y_label_column_separator of this MosaicViewProperties.

        :return: The y_label_column_separator of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @y_label_column_separator.setter
    def y_label_column_separator(self, y_label_column_separator) -> None:
        """
        Get the y_label_column_separator of this MosaicViewProperties.

        :return: The y_label_column_separator of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def y_label_columns(self):
        """
        Get the y_label_columns of this MosaicViewProperties.

        :return: The y_label_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @y_label_columns.setter
    def y_label_columns(self, y_label_columns) -> None:
        """
        Get the y_label_columns of this MosaicViewProperties.

        :return: The y_label_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @property
    def y_series_columns(self):
        """
        Get the y_series_columns of this MosaicViewProperties.

        :return: The y_series_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @y_series_columns.setter
    def y_series_columns(self, y_series_columns) -> None:
        """
        Get the y_series_columns of this MosaicViewProperties.

        :return: The y_series_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @property
    def fill_columns(self):
        """
        Get the fill_columns of this MosaicViewProperties.

        :return: The fill_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @fill_columns.setter
    def fill_columns(self, fill_columns) -> None:
        """
        Get the fill_columns of this MosaicViewProperties.

        :return: The fill_columns of this MosaicViewProperties.
        :rtype: list[str]
        """
        ...
    @property
    def x_domain(self):
        """
        Get the x_domain of this MosaicViewProperties.

        :return: The x_domain of this MosaicViewProperties.
        :rtype: list[float]
        """
        ...
    @x_domain.setter
    def x_domain(self, x_domain) -> None:
        """
        Get the x_domain of this MosaicViewProperties.

        :return: The x_domain of this MosaicViewProperties.
        :rtype: list[float]
        """
        ...
    @property
    def y_domain(self):
        """
        Get the y_domain of this MosaicViewProperties.

        :return: The y_domain of this MosaicViewProperties.
        :rtype: list[float]
        """
        ...
    @y_domain.setter
    def y_domain(self, y_domain) -> None:
        """
        Get the y_domain of this MosaicViewProperties.

        :return: The y_domain of this MosaicViewProperties.
        :rtype: list[float]
        """
        ...
    @property
    def x_axis_label(self):
        """
        Get the x_axis_label of this MosaicViewProperties.

        :return: The x_axis_label of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @x_axis_label.setter
    def x_axis_label(self, x_axis_label) -> None:
        """
        Get the x_axis_label of this MosaicViewProperties.

        :return: The x_axis_label of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def y_axis_label(self):
        """
        Get the y_axis_label of this MosaicViewProperties.

        :return: The y_axis_label of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @y_axis_label.setter
    def y_axis_label(self, y_axis_label) -> None:
        """
        Get the y_axis_label of this MosaicViewProperties.

        :return: The y_axis_label of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def x_prefix(self):
        """
        Get the x_prefix of this MosaicViewProperties.

        :return: The x_prefix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @x_prefix.setter
    def x_prefix(self, x_prefix) -> None:
        """
        Get the x_prefix of this MosaicViewProperties.

        :return: The x_prefix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def x_suffix(self):
        """
        Get the x_suffix of this MosaicViewProperties.

        :return: The x_suffix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @x_suffix.setter
    def x_suffix(self, x_suffix) -> None:
        """
        Get the x_suffix of this MosaicViewProperties.

        :return: The x_suffix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def y_prefix(self):
        """
        Get the y_prefix of this MosaicViewProperties.

        :return: The y_prefix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @y_prefix.setter
    def y_prefix(self, y_prefix) -> None:
        """
        Get the y_prefix of this MosaicViewProperties.

        :return: The y_prefix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def y_suffix(self):
        """
        Get the y_suffix of this MosaicViewProperties.

        :return: The y_suffix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @y_suffix.setter
    def y_suffix(self, y_suffix) -> None:
        """
        Get the y_suffix of this MosaicViewProperties.

        :return: The y_suffix of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def hover_dimension(self):
        """
        Get the hover_dimension of this MosaicViewProperties.

        :return: The hover_dimension of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @hover_dimension.setter
    def hover_dimension(self, hover_dimension) -> None:
        """
        Get the hover_dimension of this MosaicViewProperties.

        :return: The hover_dimension of this MosaicViewProperties.
        :rtype: str
        """
        ...
    @property
    def legend_colorize_rows(self):
        """
        Get the legend_colorize_rows of this MosaicViewProperties.

        :return: The legend_colorize_rows of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @legend_colorize_rows.setter
    def legend_colorize_rows(self, legend_colorize_rows) -> None:
        """
        Get the legend_colorize_rows of this MosaicViewProperties.

        :return: The legend_colorize_rows of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @property
    def legend_hide(self):
        """
        Get the legend_hide of this MosaicViewProperties.

        :return: The legend_hide of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @legend_hide.setter
    def legend_hide(self, legend_hide) -> None:
        """
        Get the legend_hide of this MosaicViewProperties.

        :return: The legend_hide of this MosaicViewProperties.
        :rtype: bool
        """
        ...
    @property
    def legend_opacity(self):
        """
        Get the legend_opacity of this MosaicViewProperties.

        :return: The legend_opacity of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @legend_opacity.setter
    def legend_opacity(self, legend_opacity) -> None:
        """
        Get the legend_opacity of this MosaicViewProperties.

        :return: The legend_opacity of this MosaicViewProperties.
        :rtype: float
        """
        ...
    @property
    def legend_orientation_threshold(self):
        """
        Get the legend_orientation_threshold of this MosaicViewProperties.

        :return: The legend_orientation_threshold of this MosaicViewProperties.
        :rtype: int
        """
        ...
    @legend_orientation_threshold.setter
    def legend_orientation_threshold(self, legend_orientation_threshold) -> None:
        """
        Get the legend_orientation_threshold of this MosaicViewProperties.

        :return: The legend_orientation_threshold of this MosaicViewProperties.
        :rtype: int
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
