"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class Permission:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, action: Incomplete | None = None, resource: Incomplete | None = None) -> None:
        """Permission - a model defined in OpenAPI."""
        ...
    @property
    def action(self):
        """
        Get the action of this Permission.

        :return: The action of this Permission.
        :rtype: str
        """
        ...
    @action.setter
    def action(self, action) -> None:
        """
        Get the action of this Permission.

        :return: The action of this Permission.
        :rtype: str
        """
        ...
    @property
    def resource(self):
        """
        Get the resource of this Permission.

        :return: The resource of this Permission.
        :rtype: PermissionResource
        """
        ...
    @resource.setter
    def resource(self, resource) -> None:
        """
        Get the resource of this Permission.

        :return: The resource of this Permission.
        :rtype: PermissionResource
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
