"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class QueryVariablePropertiesValues:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, query: Incomplete | None = None, language: Incomplete | None = None) -> None:
        """QueryVariablePropertiesValues - a model defined in OpenAPI."""
        ...
    @property
    def query(self):
        """
        Get the query of this QueryVariablePropertiesValues.

        :return: The query of this QueryVariablePropertiesValues.
        :rtype: str
        """
        ...
    @query.setter
    def query(self, query) -> None:
        """
        Get the query of this QueryVariablePropertiesValues.

        :return: The query of this QueryVariablePropertiesValues.
        :rtype: str
        """
        ...
    @property
    def language(self):
        """
        Get the language of this QueryVariablePropertiesValues.

        :return: The language of this QueryVariablePropertiesValues.
        :rtype: str
        """
        ...
    @language.setter
    def language(self, language) -> None:
        """
        Get the language of this QueryVariablePropertiesValues.

        :return: The language of this QueryVariablePropertiesValues.
        :rtype: str
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
