"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class RemoteConnectionUpdateRequest:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        name: Incomplete | None = None,
        description: Incomplete | None = None,
        remote_url: Incomplete | None = None,
        remote_api_token: Incomplete | None = None,
        remote_org_id: Incomplete | None = None,
        allow_insecure_tls: bool = False,
    ) -> None:
        """RemoteConnectionUpdateRequest - a model defined in OpenAPI."""
        ...
    @property
    def name(self):
        """
        Get the name of this RemoteConnectionUpdateRequest.

        :return: The name of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this RemoteConnectionUpdateRequest.

        :return: The name of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def description(self):
        """
        Get the description of this RemoteConnectionUpdateRequest.

        :return: The description of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @description.setter
    def description(self, description) -> None:
        """
        Get the description of this RemoteConnectionUpdateRequest.

        :return: The description of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def remote_url(self):
        """
        Get the remote_url of this RemoteConnectionUpdateRequest.

        :return: The remote_url of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @remote_url.setter
    def remote_url(self, remote_url) -> None:
        """
        Get the remote_url of this RemoteConnectionUpdateRequest.

        :return: The remote_url of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def remote_api_token(self):
        """
        Get the remote_api_token of this RemoteConnectionUpdateRequest.

        :return: The remote_api_token of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @remote_api_token.setter
    def remote_api_token(self, remote_api_token) -> None:
        """
        Get the remote_api_token of this RemoteConnectionUpdateRequest.

        :return: The remote_api_token of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def remote_org_id(self):
        """
        Get the remote_org_id of this RemoteConnectionUpdateRequest.

        :return: The remote_org_id of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @remote_org_id.setter
    def remote_org_id(self, remote_org_id) -> None:
        """
        Get the remote_org_id of this RemoteConnectionUpdateRequest.

        :return: The remote_org_id of this RemoteConnectionUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def allow_insecure_tls(self):
        """
        Get the allow_insecure_tls of this RemoteConnectionUpdateRequest.

        :return: The allow_insecure_tls of this RemoteConnectionUpdateRequest.
        :rtype: bool
        """
        ...
    @allow_insecure_tls.setter
    def allow_insecure_tls(self, allow_insecure_tls) -> None:
        """
        Get the allow_insecure_tls of this RemoteConnectionUpdateRequest.

        :return: The allow_insecure_tls of this RemoteConnectionUpdateRequest.
        :rtype: bool
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
