"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class ScriptUpdateRequest:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, description: Incomplete | None = None, script: Incomplete | None = None) -> None:
        """ScriptUpdateRequest - a model defined in OpenAPI."""
        ...
    @property
    def description(self):
        """
        Get the description of this ScriptUpdateRequest.

        A description of the script.

        :return: The description of this ScriptUpdateRequest.
        :rtype: str
        """
        ...
    @description.setter
    def description(self, description) -> None:
        """
        Get the description of this ScriptUpdateRequest.

        A description of the script.

        :return: The description of this ScriptUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def script(self):
        """
        Get the script of this ScriptUpdateRequest.

        The script to execute.

        :return: The script of this ScriptUpdateRequest.
        :rtype: str
        """
        ...
    @script.setter
    def script(self, script) -> None:
        """
        Get the script of this ScriptUpdateRequest.

        The script to execute.

        :return: The script of this ScriptUpdateRequest.
        :rtype: str
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
