"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class StackResources:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        api_version: Incomplete | None = None,
        resource_id: Incomplete | None = None,
        kind: Incomplete | None = None,
        template_meta_name: Incomplete | None = None,
        associations: Incomplete | None = None,
        links: Incomplete | None = None,
    ) -> None:
        """StackResources - a model defined in OpenAPI."""
        ...
    @property
    def api_version(self):
        """
        Get the api_version of this StackResources.

        :return: The api_version of this StackResources.
        :rtype: str
        """
        ...
    @api_version.setter
    def api_version(self, api_version) -> None:
        """
        Get the api_version of this StackResources.

        :return: The api_version of this StackResources.
        :rtype: str
        """
        ...
    @property
    def resource_id(self):
        """
        Get the resource_id of this StackResources.

        :return: The resource_id of this StackResources.
        :rtype: str
        """
        ...
    @resource_id.setter
    def resource_id(self, resource_id) -> None:
        """
        Get the resource_id of this StackResources.

        :return: The resource_id of this StackResources.
        :rtype: str
        """
        ...
    @property
    def kind(self):
        """
        Get the kind of this StackResources.

        :return: The kind of this StackResources.
        :rtype: TemplateKind
        """
        ...
    @kind.setter
    def kind(self, kind) -> None:
        """
        Get the kind of this StackResources.

        :return: The kind of this StackResources.
        :rtype: TemplateKind
        """
        ...
    @property
    def template_meta_name(self):
        """
        Get the template_meta_name of this StackResources.

        :return: The template_meta_name of this StackResources.
        :rtype: str
        """
        ...
    @template_meta_name.setter
    def template_meta_name(self, template_meta_name) -> None:
        """
        Get the template_meta_name of this StackResources.

        :return: The template_meta_name of this StackResources.
        :rtype: str
        """
        ...
    @property
    def associations(self):
        """
        Get the associations of this StackResources.

        :return: The associations of this StackResources.
        :rtype: list[StackAssociations]
        """
        ...
    @associations.setter
    def associations(self, associations) -> None:
        """
        Get the associations of this StackResources.

        :return: The associations of this StackResources.
        :rtype: list[StackAssociations]
        """
        ...
    @property
    def links(self):
        """
        Get the links of this StackResources.

        :return: The links of this StackResources.
        :rtype: StackLinks
        """
        ...
    @links.setter
    def links(self, links) -> None:
        """
        Get the links of this StackResources.

        :return: The links of this StackResources.
        :rtype: StackLinks
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
