"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class StackEvents:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        event_type: Incomplete | None = None,
        name: Incomplete | None = None,
        description: Incomplete | None = None,
        sources: Incomplete | None = None,
        resources: Incomplete | None = None,
        urls: Incomplete | None = None,
        updated_at: Incomplete | None = None,
    ) -> None:
        """StackEvents - a model defined in OpenAPI."""
        ...
    @property
    def event_type(self):
        """
        Get the event_type of this StackEvents.

        :return: The event_type of this StackEvents.
        :rtype: str
        """
        ...
    @event_type.setter
    def event_type(self, event_type) -> None:
        """
        Get the event_type of this StackEvents.

        :return: The event_type of this StackEvents.
        :rtype: str
        """
        ...
    @property
    def name(self):
        """
        Get the name of this StackEvents.

        :return: The name of this StackEvents.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this StackEvents.

        :return: The name of this StackEvents.
        :rtype: str
        """
        ...
    @property
    def description(self):
        """
        Get the description of this StackEvents.

        :return: The description of this StackEvents.
        :rtype: str
        """
        ...
    @description.setter
    def description(self, description) -> None:
        """
        Get the description of this StackEvents.

        :return: The description of this StackEvents.
        :rtype: str
        """
        ...
    @property
    def sources(self):
        """
        Get the sources of this StackEvents.

        :return: The sources of this StackEvents.
        :rtype: list[str]
        """
        ...
    @sources.setter
    def sources(self, sources) -> None:
        """
        Get the sources of this StackEvents.

        :return: The sources of this StackEvents.
        :rtype: list[str]
        """
        ...
    @property
    def resources(self):
        """
        Get the resources of this StackEvents.

        :return: The resources of this StackEvents.
        :rtype: list[StackResources]
        """
        ...
    @resources.setter
    def resources(self, resources) -> None:
        """
        Get the resources of this StackEvents.

        :return: The resources of this StackEvents.
        :rtype: list[StackResources]
        """
        ...
    @property
    def urls(self):
        """
        Get the urls of this StackEvents.

        :return: The urls of this StackEvents.
        :rtype: list[str]
        """
        ...
    @urls.setter
    def urls(self, urls) -> None:
        """
        Get the urls of this StackEvents.

        :return: The urls of this StackEvents.
        :rtype: list[str]
        """
        ...
    @property
    def updated_at(self):
        """
        Get the updated_at of this StackEvents.

        :return: The updated_at of this StackEvents.
        :rtype: datetime
        """
        ...
    @updated_at.setter
    def updated_at(self, updated_at) -> None:
        """
        Get the updated_at of this StackEvents.

        :return: The updated_at of this StackEvents.
        :rtype: datetime
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
