"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from typing import Any, ClassVar

from influxdb_client.domain.links import Links
from influxdb_client.domain.task import Task

class Tasks:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: ClassVar[dict[str, str]]
    attribute_map: ClassVar[dict[str, str]]

    tasks: list[Task]
    links: Links
    discriminator: None
    def __init__(self, links: Links | None = None, tasks: list[Task] | None = None) -> None:
        """Tasks - a model defined in OpenAPI."""
        ...
    def to_dict(self) -> dict[str, Any]:
        """Return the model properties as a dict."""
        ...
    def to_str(self) -> str:
        """Return the string representation of the model."""
        ...
    def __eq__(self, other: object) -> bool:
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other: object) -> bool:
        """Return true if both objects are not equal."""
        ...
