"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TaskUpdateRequest:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        status: Incomplete | None = None,
        flux: Incomplete | None = None,
        name: Incomplete | None = None,
        every: Incomplete | None = None,
        cron: Incomplete | None = None,
        offset: Incomplete | None = None,
        description: Incomplete | None = None,
    ) -> None:
        """TaskUpdateRequest - a model defined in OpenAPI."""
        ...
    @property
    def status(self):
        """
        Get the status of this TaskUpdateRequest.

        :return: The status of this TaskUpdateRequest.
        :rtype: TaskStatusType
        """
        ...
    @status.setter
    def status(self, status) -> None:
        """
        Get the status of this TaskUpdateRequest.

        :return: The status of this TaskUpdateRequest.
        :rtype: TaskStatusType
        """
        ...
    @property
    def flux(self):
        """
        Get the flux of this TaskUpdateRequest.

        The Flux script that the task runs.

        :return: The flux of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @flux.setter
    def flux(self, flux) -> None:
        """
        Get the flux of this TaskUpdateRequest.

        The Flux script that the task runs.

        :return: The flux of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def name(self):
        """
        Get the name of this TaskUpdateRequest.

        Update the 'name' option in the flux script.

        :return: The name of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this TaskUpdateRequest.

        Update the 'name' option in the flux script.

        :return: The name of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def every(self):
        """
        Get the every of this TaskUpdateRequest.

        Update the 'every' option in the flux script.

        :return: The every of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @every.setter
    def every(self, every) -> None:
        """
        Get the every of this TaskUpdateRequest.

        Update the 'every' option in the flux script.

        :return: The every of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def cron(self):
        """
        Get the cron of this TaskUpdateRequest.

        Update the 'cron' option in the flux script.

        :return: The cron of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @cron.setter
    def cron(self, cron) -> None:
        """
        Get the cron of this TaskUpdateRequest.

        Update the 'cron' option in the flux script.

        :return: The cron of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def offset(self):
        """
        Get the offset of this TaskUpdateRequest.

        Update the 'offset' option in the flux script.

        :return: The offset of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @offset.setter
    def offset(self, offset) -> None:
        """
        Get the offset of this TaskUpdateRequest.

        Update the 'offset' option in the flux script.

        :return: The offset of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @property
    def description(self):
        """
        Get the description of this TaskUpdateRequest.

        Update the description of the task.

        :return: The description of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    @description.setter
    def description(self, description) -> None:
        """
        Get the description of this TaskUpdateRequest.

        Update the description of the task.

        :return: The description of this TaskUpdateRequest.
        :rtype: str
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
