"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateExportByIDOrgIDs:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, org_id: Incomplete | None = None, resource_filters: Incomplete | None = None) -> None:
        """TemplateExportByIDOrgIDs - a model defined in OpenAPI."""
        ...
    @property
    def org_id(self):
        """
        Get the org_id of this TemplateExportByIDOrgIDs.

        :return: The org_id of this TemplateExportByIDOrgIDs.
        :rtype: str
        """
        ...
    @org_id.setter
    def org_id(self, org_id) -> None:
        """
        Get the org_id of this TemplateExportByIDOrgIDs.

        :return: The org_id of this TemplateExportByIDOrgIDs.
        :rtype: str
        """
        ...
    @property
    def resource_filters(self):
        """
        Get the resource_filters of this TemplateExportByIDOrgIDs.

        :return: The resource_filters of this TemplateExportByIDOrgIDs.
        :rtype: TemplateExportByIDResourceFilters
        """
        ...
    @resource_filters.setter
    def resource_filters(self, resource_filters) -> None:
        """
        Get the resource_filters of this TemplateExportByIDOrgIDs.

        :return: The resource_filters of this TemplateExportByIDOrgIDs.
        :rtype: TemplateExportByIDResourceFilters
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
