"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateExportByIDResources:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, id: Incomplete | None = None, kind: Incomplete | None = None, name: Incomplete | None = None) -> None:
        """TemplateExportByIDResources - a model defined in OpenAPI."""
        ...
    @property
    def id(self):
        """
        Get the id of this TemplateExportByIDResources.

        :return: The id of this TemplateExportByIDResources.
        :rtype: str
        """
        ...
    @id.setter
    def id(self, id) -> None:
        """
        Get the id of this TemplateExportByIDResources.

        :return: The id of this TemplateExportByIDResources.
        :rtype: str
        """
        ...
    @property
    def kind(self):
        """
        Get the kind of this TemplateExportByIDResources.

        :return: The kind of this TemplateExportByIDResources.
        :rtype: TemplateKind
        """
        ...
    @kind.setter
    def kind(self, kind) -> None:
        """
        Get the kind of this TemplateExportByIDResources.

        :return: The kind of this TemplateExportByIDResources.
        :rtype: TemplateKind
        """
        ...
    @property
    def name(self):
        """
        Get the name of this TemplateExportByIDResources.

        if defined with id, name is used for resource exported by id. if defined independently, resources strictly matching name are exported

        :return: The name of this TemplateExportByIDResources.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this TemplateExportByIDResources.

        if defined with id, name is used for resource exported by id. if defined independently, resources strictly matching name are exported

        :return: The name of this TemplateExportByIDResources.
        :rtype: str
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
