"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateSummaryErrors:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        kind: Incomplete | None = None,
        reason: Incomplete | None = None,
        fields: Incomplete | None = None,
        indexes: Incomplete | None = None,
    ) -> None:
        """TemplateSummaryErrors - a model defined in OpenAPI."""
        ...
    @property
    def kind(self):
        """
        Get the kind of this TemplateSummaryErrors.

        :return: The kind of this TemplateSummaryErrors.
        :rtype: TemplateKind
        """
        ...
    @kind.setter
    def kind(self, kind) -> None:
        """
        Get the kind of this TemplateSummaryErrors.

        :return: The kind of this TemplateSummaryErrors.
        :rtype: TemplateKind
        """
        ...
    @property
    def reason(self):
        """
        Get the reason of this TemplateSummaryErrors.

        :return: The reason of this TemplateSummaryErrors.
        :rtype: str
        """
        ...
    @reason.setter
    def reason(self, reason) -> None:
        """
        Get the reason of this TemplateSummaryErrors.

        :return: The reason of this TemplateSummaryErrors.
        :rtype: str
        """
        ...
    @property
    def fields(self):
        """
        Get the fields of this TemplateSummaryErrors.

        :return: The fields of this TemplateSummaryErrors.
        :rtype: list[str]
        """
        ...
    @fields.setter
    def fields(self, fields) -> None:
        """
        Get the fields of this TemplateSummaryErrors.

        :return: The fields of this TemplateSummaryErrors.
        :rtype: list[str]
        """
        ...
    @property
    def indexes(self):
        """
        Get the indexes of this TemplateSummaryErrors.

        :return: The indexes of this TemplateSummaryErrors.
        :rtype: list[int]
        """
        ...
    @indexes.setter
    def indexes(self, indexes) -> None:
        """
        Get the indexes of this TemplateSummaryErrors.

        :return: The indexes of this TemplateSummaryErrors.
        :rtype: list[int]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
