"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateExportByName:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self, stack_id: Incomplete | None = None, org_ids: Incomplete | None = None, resources: Incomplete | None = None
    ) -> None:
        """TemplateExportByName - a model defined in OpenAPI."""
        ...
    @property
    def stack_id(self):
        """
        Get the stack_id of this TemplateExportByName.

        :return: The stack_id of this TemplateExportByName.
        :rtype: str
        """
        ...
    @stack_id.setter
    def stack_id(self, stack_id) -> None:
        """
        Get the stack_id of this TemplateExportByName.

        :return: The stack_id of this TemplateExportByName.
        :rtype: str
        """
        ...
    @property
    def org_ids(self):
        """
        Get the org_ids of this TemplateExportByName.

        :return: The org_ids of this TemplateExportByName.
        :rtype: list[TemplateExportByIDOrgIDs]
        """
        ...
    @org_ids.setter
    def org_ids(self, org_ids) -> None:
        """
        Get the org_ids of this TemplateExportByName.

        :return: The org_ids of this TemplateExportByName.
        :rtype: list[TemplateExportByIDOrgIDs]
        """
        ...
    @property
    def resources(self):
        """
        Get the resources of this TemplateExportByName.

        :return: The resources of this TemplateExportByName.
        :rtype: list[TemplateExportByNameResources]
        """
        ...
    @resources.setter
    def resources(self, resources) -> None:
        """
        Get the resources of this TemplateExportByName.

        :return: The resources of this TemplateExportByName.
        :rtype: list[TemplateExportByNameResources]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
