"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateSummaryLabel:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        id: Incomplete | None = None,
        org_id: Incomplete | None = None,
        kind: Incomplete | None = None,
        template_meta_name: Incomplete | None = None,
        name: Incomplete | None = None,
        properties: Incomplete | None = None,
        env_references: Incomplete | None = None,
    ) -> None:
        """TemplateSummaryLabel - a model defined in OpenAPI."""
        ...
    @property
    def id(self):
        """
        Get the id of this TemplateSummaryLabel.

        :return: The id of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @id.setter
    def id(self, id) -> None:
        """
        Get the id of this TemplateSummaryLabel.

        :return: The id of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @property
    def org_id(self):
        """
        Get the org_id of this TemplateSummaryLabel.

        :return: The org_id of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @org_id.setter
    def org_id(self, org_id) -> None:
        """
        Get the org_id of this TemplateSummaryLabel.

        :return: The org_id of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @property
    def kind(self):
        """
        Get the kind of this TemplateSummaryLabel.

        :return: The kind of this TemplateSummaryLabel.
        :rtype: TemplateKind
        """
        ...
    @kind.setter
    def kind(self, kind) -> None:
        """
        Get the kind of this TemplateSummaryLabel.

        :return: The kind of this TemplateSummaryLabel.
        :rtype: TemplateKind
        """
        ...
    @property
    def template_meta_name(self):
        """
        Get the template_meta_name of this TemplateSummaryLabel.

        :return: The template_meta_name of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @template_meta_name.setter
    def template_meta_name(self, template_meta_name) -> None:
        """
        Get the template_meta_name of this TemplateSummaryLabel.

        :return: The template_meta_name of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @property
    def name(self):
        """
        Get the name of this TemplateSummaryLabel.

        :return: The name of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @name.setter
    def name(self, name) -> None:
        """
        Get the name of this TemplateSummaryLabel.

        :return: The name of this TemplateSummaryLabel.
        :rtype: str
        """
        ...
    @property
    def properties(self):
        """
        Get the properties of this TemplateSummaryLabel.

        :return: The properties of this TemplateSummaryLabel.
        :rtype: TemplateSummaryLabelProperties
        """
        ...
    @properties.setter
    def properties(self, properties) -> None:
        """
        Get the properties of this TemplateSummaryLabel.

        :return: The properties of this TemplateSummaryLabel.
        :rtype: TemplateSummaryLabelProperties
        """
        ...
    @property
    def env_references(self):
        """
        Get the env_references of this TemplateSummaryLabel.

        :return: The env_references of this TemplateSummaryLabel.
        :rtype: list[object]
        """
        ...
    @env_references.setter
    def env_references(self, env_references) -> None:
        """
        Get the env_references of this TemplateSummaryLabel.

        :return: The env_references of this TemplateSummaryLabel.
        :rtype: list[object]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
