"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateSummaryDiff:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(
        self,
        buckets: Incomplete | None = None,
        checks: Incomplete | None = None,
        dashboards: Incomplete | None = None,
        labels: Incomplete | None = None,
        label_mappings: Incomplete | None = None,
        notification_endpoints: Incomplete | None = None,
        notification_rules: Incomplete | None = None,
        tasks: Incomplete | None = None,
        telegraf_configs: Incomplete | None = None,
        variables: Incomplete | None = None,
    ) -> None:
        """TemplateSummaryDiff - a model defined in OpenAPI."""
        ...
    @property
    def buckets(self):
        """
        Get the buckets of this TemplateSummaryDiff.

        :return: The buckets of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffBuckets]
        """
        ...
    @buckets.setter
    def buckets(self, buckets) -> None:
        """
        Get the buckets of this TemplateSummaryDiff.

        :return: The buckets of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffBuckets]
        """
        ...
    @property
    def checks(self):
        """
        Get the checks of this TemplateSummaryDiff.

        :return: The checks of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffChecks]
        """
        ...
    @checks.setter
    def checks(self, checks) -> None:
        """
        Get the checks of this TemplateSummaryDiff.

        :return: The checks of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffChecks]
        """
        ...
    @property
    def dashboards(self):
        """
        Get the dashboards of this TemplateSummaryDiff.

        :return: The dashboards of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffDashboards]
        """
        ...
    @dashboards.setter
    def dashboards(self, dashboards) -> None:
        """
        Get the dashboards of this TemplateSummaryDiff.

        :return: The dashboards of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffDashboards]
        """
        ...
    @property
    def labels(self):
        """
        Get the labels of this TemplateSummaryDiff.

        :return: The labels of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffLabels]
        """
        ...
    @labels.setter
    def labels(self, labels) -> None:
        """
        Get the labels of this TemplateSummaryDiff.

        :return: The labels of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffLabels]
        """
        ...
    @property
    def label_mappings(self):
        """
        Get the label_mappings of this TemplateSummaryDiff.

        :return: The label_mappings of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffLabelMappings]
        """
        ...
    @label_mappings.setter
    def label_mappings(self, label_mappings) -> None:
        """
        Get the label_mappings of this TemplateSummaryDiff.

        :return: The label_mappings of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffLabelMappings]
        """
        ...
    @property
    def notification_endpoints(self):
        """
        Get the notification_endpoints of this TemplateSummaryDiff.

        :return: The notification_endpoints of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffNotificationEndpoints]
        """
        ...
    @notification_endpoints.setter
    def notification_endpoints(self, notification_endpoints) -> None:
        """
        Get the notification_endpoints of this TemplateSummaryDiff.

        :return: The notification_endpoints of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffNotificationEndpoints]
        """
        ...
    @property
    def notification_rules(self):
        """
        Get the notification_rules of this TemplateSummaryDiff.

        :return: The notification_rules of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffNotificationRules]
        """
        ...
    @notification_rules.setter
    def notification_rules(self, notification_rules) -> None:
        """
        Get the notification_rules of this TemplateSummaryDiff.

        :return: The notification_rules of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffNotificationRules]
        """
        ...
    @property
    def tasks(self):
        """
        Get the tasks of this TemplateSummaryDiff.

        :return: The tasks of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffTasks]
        """
        ...
    @tasks.setter
    def tasks(self, tasks) -> None:
        """
        Get the tasks of this TemplateSummaryDiff.

        :return: The tasks of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffTasks]
        """
        ...
    @property
    def telegraf_configs(self):
        """
        Get the telegraf_configs of this TemplateSummaryDiff.

        :return: The telegraf_configs of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffTelegrafConfigs]
        """
        ...
    @telegraf_configs.setter
    def telegraf_configs(self, telegraf_configs) -> None:
        """
        Get the telegraf_configs of this TemplateSummaryDiff.

        :return: The telegraf_configs of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffTelegrafConfigs]
        """
        ...
    @property
    def variables(self):
        """
        Get the variables of this TemplateSummaryDiff.

        :return: The variables of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffVariables]
        """
        ...
    @variables.setter
    def variables(self, variables) -> None:
        """
        Get the variables of this TemplateSummaryDiff.

        :return: The variables of this TemplateSummaryDiff.
        :rtype: list[TemplateSummaryDiffVariables]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
