"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

class TemplateExportByIDResourceFilters:
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    openapi_types: Incomplete
    attribute_map: Incomplete
    discriminator: Incomplete
    def __init__(self, by_label: Incomplete | None = None, by_resource_kind: Incomplete | None = None) -> None:
        """TemplateExportByIDResourceFilters - a model defined in OpenAPI."""
        ...
    @property
    def by_label(self):
        """
        Get the by_label of this TemplateExportByIDResourceFilters.

        :return: The by_label of this TemplateExportByIDResourceFilters.
        :rtype: list[str]
        """
        ...
    @by_label.setter
    def by_label(self, by_label) -> None:
        """
        Get the by_label of this TemplateExportByIDResourceFilters.

        :return: The by_label of this TemplateExportByIDResourceFilters.
        :rtype: list[str]
        """
        ...
    @property
    def by_resource_kind(self):
        """
        Get the by_resource_kind of this TemplateExportByIDResourceFilters.

        :return: The by_resource_kind of this TemplateExportByIDResourceFilters.
        :rtype: list[TemplateKind]
        """
        ...
    @by_resource_kind.setter
    def by_resource_kind(self, by_resource_kind) -> None:
        """
        Get the by_resource_kind of this TemplateExportByIDResourceFilters.

        :return: The by_resource_kind of this TemplateExportByIDResourceFilters.
        :rtype: list[TemplateKind]
        """
        ...
    def to_dict(self):
        """Return the model properties as a dict."""
        ...
    def to_str(self):
        """Return the string representation of the model."""
        ...
    def __eq__(self, other):
        """Return true if both objects are equal."""
        ...
    def __ne__(self, other):
        """Return true if both objects are not equal."""
        ...
