"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from urllib3 import HTTPResponse

from ._sync.rest import RESTResponse
from .client.exceptions import InfluxDBError

class ApiException(InfluxDBError):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech
    Do not edit the class manually.
    """
    status: Incomplete
    reason: Incomplete
    body: Incomplete
    headers: Incomplete
    def __init__(
        self,
        status: Incomplete | None = None,
        reason: Incomplete | None = None,
        http_resp: HTTPResponse | RESTResponse | None = None,
    ) -> None:
        """Initialize with HTTP response."""
        ...

class _BaseRESTClient:
    logger: Incomplete
    @staticmethod
    def log_request(method: str, url: str): ...
    @staticmethod
    def log_response(status: str): ...
    @staticmethod
    def log_body(body: object, prefix: str): ...
    @staticmethod
    def log_headers(headers: dict[str, str], prefix: str): ...
