import datetime

class DayCount:
    """A day count converter for the given epoch (in terms of Julian Day Count)"""
    epoch: float
    def __init__(self, epoch: float) -> None: ...
    def to_gregorian(self, dc: int) -> tuple[int, int, int]:
        """From day count to Gregorian (year, month, day) tuple"""
        ...
    def from_gregorian(self, year: int, month: int, day: int) -> float: ...
    def to_jd(self, dc: int) -> float: ...
    def from_jd(self, jdc: float) -> float: ...
    def from_julian(self, year: int, month: int, day: int) -> float: ...
    def to_julian(self, dc: int) -> tuple[int, int, int]:
        """From day count to Julian (year, month, day) tuple"""
        ...
    def to_datetime(self, dc: int) -> datetime.datetime: ...
    def from_datetime(self, date: datetime.datetime) -> float: ...
