"""
The Dublin day count is a truncated `Julian day <julian.html>`__ with an epoch of noon on December 31, 1899.

This is a convenience module, it uses :doc:`daycount` class for all functions.
"""

import datetime
from typing import Final

EPOCH: Final = 2415020

def to_gregorian(dc: int) -> tuple[int, int, int]:
    """From day count to Gregorian (year, month, day) tuple"""
    ...
def from_gregorian(year: int, month: int, day: int) -> float: ...
def to_jd(dc: int) -> float: ...
def from_jd(jdc: float) -> float: ...
def from_julian(year: int, month: int, day: int) -> float: ...
def to_julian(dc: int) -> tuple[int, int, int]:
    """From day count to Julian (year, month, day) tuple"""
    ...
def to_datetime(dc: int) -> datetime.datetime: ...
def from_datetime(date: datetime.datetime) -> float: ...
