from . import base

class Filter(base.Filter):
    """Removes optional tags from the token stream"""
    def slider(self) -> None: ...
    def __iter__(self): ...
    def is_optional_start(self, tagname, previous, next): ...
    def is_optional_end(self, tagname, next): ...
