"""
DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from _typeshed import Incomplete

from tensorflow.keras.optimizers import legacy as legacy, schedules as schedules

Optimizer = Incomplete

def __getattr__(name: str) -> Incomplete: ...
