from _typeshed import Incomplete
from typing import Final

from authlib.jose import JWTClaims

class ClientRegistrationEndpoint:
    """
    The client registration endpoint is an OAuth 2.0 endpoint designed to
    allow a client to be registered with the authorization server.
    """
    ENDPOINT_NAME: Final = "client_registration"
    software_statement_alg_values_supported: Incomplete
    server: Incomplete
    claims_classes: list[type[Incomplete]]
    def __init__(self, server=None, claims_classes: list[type[Incomplete]] | None = None) -> None: ...
    def __call__(self, request) -> dict[Incomplete, Incomplete]: ...
    def create_registration_response(self, request): ...
    def extract_client_metadata(self, request): ...
    def extract_software_statement(self, software_statement, request) -> JWTClaims: ...
    def generate_client_info(self, request) -> dict[str, Incomplete]: ...
    def generate_client_registration_info(self, client, request) -> None:
        """
        Generate ```registration_client_uri`` and ``registration_access_token``
        for RFC7592. This method returns ``None`` by default. Developers MAY rewrite
        this method to return registration information.
        """
        ...
    def create_endpoint_request(self, request): ...
    def generate_client_id(self, request) -> str: ...
    def generate_client_secret(self, request) -> str: ...
    def get_server_metadata(self): ...
    def authenticate_token(self, request): ...
    def resolve_public_key(self, request): ...
    def save_client(self, client_info, client_metadata, request): ...
