"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from influxdb_client.service._base_service import _BaseService

class OrganizationsService(_BaseService):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    def __init__(self, api_client: Incomplete | None = None) -> None:
        """OrganizationsService - a operation defined in OpenAPI."""
        ...
    def delete_orgs_id(self, org_id, **kwargs):
        """
        Delete an organization.

        Deletes an organization.  Deleting an organization from InfluxDB Cloud can't be undone. Once deleted, all data associated with the organization is removed.  #### InfluxDB Cloud  - Does the following when you send a delete request:    1. Validates the request and queues the delete.   2. Returns an HTTP `204` status code if queued; _error_ otherwise.   3. Handles the delete asynchronously.  #### InfluxDB OSS  - Validates the request, handles the delete synchronously, and then responds with success or failure.  #### Limitations  - Only one organization can be deleted per request.  #### Related guides  - [Delete organizations](https://docs.influxdata.com/influxdb/latest/organizations/delete-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to delete. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def delete_orgs_id_with_http_info(self, org_id, **kwargs):
        """
        Delete an organization.

        Deletes an organization.  Deleting an organization from InfluxDB Cloud can't be undone. Once deleted, all data associated with the organization is removed.  #### InfluxDB Cloud  - Does the following when you send a delete request:    1. Validates the request and queues the delete.   2. Returns an HTTP `204` status code if queued; _error_ otherwise.   3. Handles the delete asynchronously.  #### InfluxDB OSS  - Validates the request, handles the delete synchronously, and then responds with success or failure.  #### Limitations  - Only one organization can be deleted per request.  #### Related guides  - [Delete organizations](https://docs.influxdata.com/influxdb/latest/organizations/delete-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id_with_http_info(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to delete. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def delete_orgs_id_async(self, org_id, **kwargs):
        """
        Delete an organization.

        Deletes an organization.  Deleting an organization from InfluxDB Cloud can't be undone. Once deleted, all data associated with the organization is removed.  #### InfluxDB Cloud  - Does the following when you send a delete request:    1. Validates the request and queues the delete.   2. Returns an HTTP `204` status code if queued; _error_ otherwise.   3. Handles the delete asynchronously.  #### InfluxDB OSS  - Validates the request, handles the delete synchronously, and then responds with success or failure.  #### Limitations  - Only one organization can be deleted per request.  #### Related guides  - [Delete organizations](https://docs.influxdata.com/influxdb/latest/organizations/delete-orgs/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization to delete. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def delete_orgs_id_members_id(self, user_id, org_id, **kwargs):
        """
        Remove a member from an organization.

        Removes a member from an organization.  Use this endpoint to remove a user's member privileges for an organization. Removing member privileges removes the user's `read` and `write` permissions from the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related guides  - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id_members_id(user_id, org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove a user from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def delete_orgs_id_members_id_with_http_info(self, user_id, org_id, **kwargs):
        """
        Remove a member from an organization.

        Removes a member from an organization.  Use this endpoint to remove a user's member privileges for an organization. Removing member privileges removes the user's `read` and `write` permissions from the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related guides  - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id_members_id_with_http_info(user_id, org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove a user from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def delete_orgs_id_members_id_async(self, user_id, org_id, **kwargs):
        """
        Remove a member from an organization.

        Removes a member from an organization.  Use this endpoint to remove a user's member privileges for an organization. Removing member privileges removes the user's `read` and `write` permissions from the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related guides  - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove a user from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def delete_orgs_id_owners_id(self, user_id, org_id, **kwargs):
        """
        Remove an owner from an organization.

        Removes an [owner](https://docs.influxdata.com/influxdb/latest/reference/glossary/#owner) from the organization.  Organization owners have permission to delete organizations and remove user and member permissions from the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Owner permissions are separate from API token permissions. - Owner permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related endpoints - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id_owners_id(user_id, org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove an owner from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def delete_orgs_id_owners_id_with_http_info(self, user_id, org_id, **kwargs):
        """
        Remove an owner from an organization.

        Removes an [owner](https://docs.influxdata.com/influxdb/latest/reference/glossary/#owner) from the organization.  Organization owners have permission to delete organizations and remove user and member permissions from the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Owner permissions are separate from API token permissions. - Owner permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related endpoints - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_orgs_id_owners_id_with_http_info(user_id, org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove an owner from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def delete_orgs_id_owners_id_async(self, user_id, org_id, **kwargs):
        """
        Remove an owner from an organization.

        Removes an [owner](https://docs.influxdata.com/influxdb/latest/reference/glossary/#owner) from the organization.  Organization owners have permission to delete organizations and remove user and member permissions from the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Owner permissions are separate from API token permissions. - Owner permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an owner from.  #### Related endpoints - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str user_id: The ID of the user to remove. (required)
        :param str org_id: The ID of the organization to remove an owner from. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs(self, **kwargs):
        """
        List organizations.

        Lists [organizations](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization/).  To limit which organizations are returned, pass query parameters in your request. If no query parameters are passed, InfluxDB returns all organizations up to the default `limit`.  #### InfluxDB Cloud  - Only returns the organization that owns the token passed in the request.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param int offset: The offset for pagination. The number of records to skip.  For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/latest/api/#tag/Pagination).
        :param int limit: Limits the number of records returned. Default is `20`.
        :param bool descending:
        :param str org: An organization name. Only returns the specified organization.
        :param str org_id: An organization ID. Only returns the specified organization.
        :param str user_id: A user ID. Only returns organizations where the specified user is a member or owner.
        :return: Organizations
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_with_http_info(self, **kwargs):
        """
        List organizations.

        Lists [organizations](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization/).  To limit which organizations are returned, pass query parameters in your request. If no query parameters are passed, InfluxDB returns all organizations up to the default `limit`.  #### InfluxDB Cloud  - Only returns the organization that owns the token passed in the request.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param int offset: The offset for pagination. The number of records to skip.  For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/latest/api/#tag/Pagination).
        :param int limit: Limits the number of records returned. Default is `20`.
        :param bool descending:
        :param str org: An organization name. Only returns the specified organization.
        :param str org_id: An organization ID. Only returns the specified organization.
        :param str user_id: A user ID. Only returns organizations where the specified user is a member or owner.
        :return: Organizations
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def get_orgs_async(self, **kwargs):
        """
        List organizations.

        Lists [organizations](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization/).  To limit which organizations are returned, pass query parameters in your request. If no query parameters are passed, InfluxDB returns all organizations up to the default `limit`.  #### InfluxDB Cloud  - Only returns the organization that owns the token passed in the request.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param int offset: The offset for pagination. The number of records to skip.  For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/latest/api/#tag/Pagination).
        :param int limit: Limits the number of records returned. Default is `20`.
        :param bool descending:
        :param str org: An organization name. Only returns the specified organization.
        :param str org_id: An organization ID. Only returns the specified organization.
        :param str user_id: A user ID. Only returns organizations where the specified user is a member or owner.
        :return: Organizations
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id(self, org_id, **kwargs):
        """
        Retrieve an organization.

        Retrieves an organization.  Use this endpoint to retrieve information for a specific organization.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id_with_http_info(self, org_id, **kwargs):
        """
        Retrieve an organization.

        Retrieves an organization.  Use this endpoint to retrieve information for a specific organization.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id_with_http_info(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def get_orgs_id_async(self, org_id, **kwargs):
        """
        Retrieve an organization.

        Retrieves an organization.  Use this endpoint to retrieve information for a specific organization.  #### Related guides  - [View organizations](https://docs.influxdata.com/influxdb/latest/organizations/view-orgs/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id_members(self, org_id, **kwargs):
        """
        List all members of an organization.

        Lists all users that belong to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve members for.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id_members(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve users for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMembers
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id_members_with_http_info(self, org_id, **kwargs):
        """
        List all members of an organization.

        Lists all users that belong to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve members for.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id_members_with_http_info(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve users for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMembers
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def get_orgs_id_members_async(self, org_id, **kwargs):
        """
        List all members of an organization.

        Lists all users that belong to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve members for.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization to retrieve users for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMembers
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id_owners(self, org_id, **kwargs):
        """
        List all owners of an organization.

        Lists all owners of an organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve a list of owners from.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id_owners(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to list owners for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwners
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_orgs_id_owners_with_http_info(self, org_id, **kwargs):
        """
        List all owners of an organization.

        Lists all owners of an organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve a list of owners from.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_orgs_id_owners_with_http_info(org_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to list owners for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwners
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def get_orgs_id_owners_async(self, org_id, **kwargs):
        """
        List all owners of an organization.

        Lists all owners of an organization.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `read-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve a list of owners from.
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization to list owners for. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwners
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def patch_orgs_id(self, org_id, patch_organization_request, **kwargs):
        """
        Update an organization.

        Updates an organization.  Use this endpoint to update properties (`name`, `description`) of an organization.  Updating an organization’s name affects all resources that reference the organization by name, including the following:  - Queries - Dashboards - Tasks - Telegraf configurations - Templates  If you change an organization name, be sure to update the organization name in these resources as well.  #### Related Guides  - [Update an organization](https://docs.influxdata.com/influxdb/latest/organizations/update-org/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_orgs_id(org_id, patch_organization_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to update. (required)
        :param PatchOrganizationRequest patch_organization_request: The organization update to apply. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def patch_orgs_id_with_http_info(self, org_id, patch_organization_request, **kwargs):
        """
        Update an organization.

        Updates an organization.  Use this endpoint to update properties (`name`, `description`) of an organization.  Updating an organization’s name affects all resources that reference the organization by name, including the following:  - Queries - Dashboards - Tasks - Telegraf configurations - Templates  If you change an organization name, be sure to update the organization name in these resources as well.  #### Related Guides  - [Update an organization](https://docs.influxdata.com/influxdb/latest/organizations/update-org/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_orgs_id_with_http_info(org_id, patch_organization_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization to update. (required)
        :param PatchOrganizationRequest patch_organization_request: The organization update to apply. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def patch_orgs_id_async(self, org_id, patch_organization_request, **kwargs):
        """
        Update an organization.

        Updates an organization.  Use this endpoint to update properties (`name`, `description`) of an organization.  Updating an organization’s name affects all resources that reference the organization by name, including the following:  - Queries - Dashboards - Tasks - Telegraf configurations - Templates  If you change an organization name, be sure to update the organization name in these resources as well.  #### Related Guides  - [Update an organization](https://docs.influxdata.com/influxdb/latest/organizations/update-org/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization to update. (required)
        :param PatchOrganizationRequest patch_organization_request: The organization update to apply. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs(self, post_organization_request, **kwargs):
        """
        Create an organization.

        Creates an [organization](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization) and returns the newly created organization.  #### InfluxDB Cloud  - Doesn't allow you to use this endpoint to create organizations.  #### Related guides  - [Manage organizations](https://docs.influxdata.com/influxdb/latest/organizations)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs(post_organization_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostOrganizationRequest post_organization_request: The organization to create. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs_with_http_info(self, post_organization_request, **kwargs):
        """
        Create an organization.

        Creates an [organization](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization) and returns the newly created organization.  #### InfluxDB Cloud  - Doesn't allow you to use this endpoint to create organizations.  #### Related guides  - [Manage organizations](https://docs.influxdata.com/influxdb/latest/organizations)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs_with_http_info(post_organization_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param PostOrganizationRequest post_organization_request: The organization to create. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def post_orgs_async(self, post_organization_request, **kwargs):
        """
        Create an organization.

        Creates an [organization](https://docs.influxdata.com/influxdb/latest/reference/glossary/#organization) and returns the newly created organization.  #### InfluxDB Cloud  - Doesn't allow you to use this endpoint to create organizations.  #### Related guides  - [Manage organizations](https://docs.influxdata.com/influxdb/latest/organizations)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param PostOrganizationRequest post_organization_request: The organization to create. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: Organization
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs_id_members(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add a member to an organization.

        Add a user to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add a member to.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs_id_members(org_id, add_resource_member_request_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add to the organization.  (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMember
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs_id_members_with_http_info(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add a member to an organization.

        Add a user to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add a member to.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs_id_members_with_http_info(org_id, add_resource_member_request_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add to the organization.  (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMember
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def post_orgs_id_members_async(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add a member to an organization.

        Add a user to an organization.  InfluxDB [users](https://docs.influxdata.com/influxdb/latest/reference/glossary/#user) have permission to access InfluxDB.  [Members](https://docs.influxdata.com/influxdb/latest/reference/glossary/#member) are users within the organization.  #### InfluxDB Cloud - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Limitations  - Member permissions are separate from API token permissions. - Member permissions are used in the context of the InfluxDB UI.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add a member to.  #### Related guides  - [Manage users](https://docs.influxdata.com/influxdb/latest/users/) - [Manage members](https://docs.influxdata.com/influxdb/latest/organizations/members/)
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add to the organization.  (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceMember
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs_id_owners(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add an owner to an organization.

        Adds an owner to an organization.  Use this endpoint to assign the organization `owner` role to a user.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add an owner for.  #### Related endpoints  - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs_id_owners(org_id, add_resource_member_request_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization that you want to add an owner for. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add as an owner of the organization. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwner
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def post_orgs_id_owners_with_http_info(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add an owner to an organization.

        Adds an owner to an organization.  Use this endpoint to assign the organization `owner` role to a user.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add an owner for.  #### Related endpoints  - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_orgs_id_owners_with_http_info(org_id, add_resource_member_request_body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str org_id: The ID of the organization that you want to add an owner for. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add as an owner of the organization. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwner
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def post_orgs_id_owners_async(self, org_id, add_resource_member_request_body, **kwargs):
        """
        Add an owner to an organization.

        Adds an owner to an organization.  Use this endpoint to assign the organization `owner` role to a user.  #### InfluxDB Cloud  - Doesn't use `owner` and `member` roles.   Use [`/api/v2/authorizations`](#tag/Authorizations-(API-tokens)) to assign user permissions.  #### Required permissions  - `write-orgs INFLUX_ORG_ID`  *`INFLUX_ORG_ID`* is the ID of the organization that you want to add an owner for.  #### Related endpoints  - [Authorizations](#tag/Authorizations-(API-tokens))
        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str org_id: The ID of the organization that you want to add an owner for. (required)
        :param AddResourceMemberRequestBody add_resource_member_request_body: The user to add as an owner of the organization. (required)
        :param str zap_trace_span: OpenTracing span context
        :return: ResourceOwner
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
