"""
InfluxDB OSS API Service.

The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.   # noqa: E501

OpenAPI spec version: 2.0.0
Generated by: https://openapi-generator.tech
"""

from _typeshed import Incomplete

from influxdb_client.service._base_service import _BaseService

class TelegrafPluginsService(_BaseService):
    """
    NOTE: This class is auto generated by OpenAPI Generator.

    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    def __init__(self, api_client: Incomplete | None = None) -> None:
        """TelegrafPluginsService - a operation defined in OpenAPI."""
        ...
    def get_telegraf_plugins(self, **kwargs):
        """
        List all Telegraf plugins.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_telegraf_plugins(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param str type: The type of plugin desired.
        :return: TelegrafPlugins
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    def get_telegraf_plugins_with_http_info(self, **kwargs):
        """
        List all Telegraf plugins.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_telegraf_plugins_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param str type: The type of plugin desired.
        :return: TelegrafPlugins
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
    async def get_telegraf_plugins_async(self, **kwargs):
        """
        List all Telegraf plugins.

        This method makes an asynchronous HTTP request.

        :param async_req bool
        :param str zap_trace_span: OpenTracing span context
        :param str type: The type of plugin desired.
        :return: TelegrafPlugins
                 If the method is called asynchronously,
                 returns the request thread.
        """
        ...
