import datetime

from ..core import WesternCalendar

class Guernsey(WesternCalendar):
    """Guernsey"""
    def get_spring_bank_holiday(self, year: int) -> tuple[datetime.date, str]: ...
    def get_early_may_bank_holiday(self, year: int) -> tuple[datetime.date, str]:
        """Return Early May bank holiday"""
        ...
    def get_summer_bank_holiday(self, year: int) -> tuple[datetime.date, str]: ...
    def get_liberation_day(self, year: int) -> tuple[datetime.date, str]: ...
