from ..core import WesternCalendar

class Spain(WesternCalendar):
    """Spain"""
    ...
class Andalusia(Spain):
    """Andalusia"""
    ...
class Aragon(Spain):
    """Aragon"""
    ...
class CastileAndLeon(Spain):
    """Castile and León"""
    ...
class CastillaLaMancha(Spain):
    """Castilla-La Mancha"""
    ...
class CanaryIslands(Spain):
    """Canary Islands"""
    ...
class Catalonia(Spain):
    """Catalonia"""
    ...
class Extremadura(Spain):
    """Extremadura"""
    ...
class Galicia(Spain):
    """Galicia"""
    ...
class BalearicIslands(Spain):
    """Balearic Islands"""
    ...
class LaRioja(Spain):
    """La Rioja"""
    ...
class CommunityofMadrid(Spain):
    """Community of Madrid"""
    ...
class Murcia(Spain):
    """Region of Murcia"""
    ...
class Navarre(Spain):
    """Navarre"""
    ...
class Asturias(Spain):
    """Asturias"""
    ...
class BasqueCountry(Spain):
    """Basque Country"""
    ...
class Cantabria(Spain):
    """Cantabria"""
    ...
class ValencianCommunity(Spain):
    """Valencian Community"""
    ...
