from _typeshed import Incomplete
from typing import Any

PATTERN: Any

class FreshnessDateDataParser:
    """Parses date string like "1 year, 2 months ago" and "3 hours, 50 minutes ago" """
    def get_local_tz(self): ...
    def parse(self, date_string, settings): ...
    def get_kwargs(self, date_string): ...
    def get_date_data(self, date_string, settings: Incomplete | None = None): ...

freshness_date_parser: Any
