from authlib.oidc.core.claims import UserInfo

class OpenIDMixin:
    def fetch_jwk_set(self, force: bool = False): ...
    def userinfo(self, **kwargs) -> UserInfo:
        """Fetch user info from ``userinfo_endpoint``."""
        ...
    def parse_id_token(self, token, nonce, claims_options=None, claims_cls=None, leeway: int = 120) -> UserInfo | None:
        """Return an instance of UserInfo from token's ``id_token``."""
        ...
    def create_load_key(self): ...
